// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ookegebzsduvzvfjbjjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9va2VnZWJ6c2R1dnp2ZmpiampzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjcwNzQsImV4cCI6MjA2MzE0MzA3NH0.bMpf0A-A2Fr9tbwRiPGi7eO98KWAhPLffWJwNlWCN_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);